USE BasicMySqlSyntax;

INSERT into skills VALUES
  ('Algorithms'),
  ('Analytical'),
  ('Analytics'),
  ('Analyze Data'),
  ('Applications'),
  ('Application Development'),
  ('Application Development Methodologies'),
  ('Application Development Techniques'),
  ('Architecture'),
  ('Application Programming Interfaces'),
  ('Application Development Tools'),
  ('Aspect Oriented Programming'),
  ('Computer Platforms'),
  ('Computer Science'),
  ('Database Management Systems (DBMS)'),
  ('Data Analytics'),
  ('Documentation'),
  ('Embedded Hardware'),
  ('Emerging Technologies'),
  ('Hardware'),
  ('HTML Authoring Tools'),
  ('Industry Systems'),
  ('iOS'),
  ('Information Systems'),
  ('Linux'),
  ('MacOS'),
  ('Math'),
  ('Mobile'),
  ('Operating Systems'),
  ('Parallel Processing'),
  ('Planning'),
  ('Post Object Programming'),
  ('Programming Methodologies'),
  ('Quality Control'),
  ('Relational Databases'),
  ('Relational Programming'),
  ('Revision Control'),
  ('Self-Motivation'),
  ('Structured Query Language (SQL)'),
  ('Symbolic Programming'),
  ('System Architecture'),
  ('Teamwork'),
  ('UNIX'),
  ('Web'),
  ('Windowing Systems'),
  ('Windows');
